### ISSUE TITLE
Babel fails to create a translation after MODX upgrade to v2.7.0

### ISSUE THREAD

**Issue by p-boiko** [mikrobi/babel#174]
### Summary
Babel fails to create translation for resource.

### Step to reproduce
Open any resource or create a new one, click Create translation in any context you have.

### Observed behavior
"Please wait" alert shows up and hangs there forever.
In the console I see the following errors: JS requires assets/components/babel/conn/mgr.php through ajax request but fails with 404 server response.
But the script exists: https://i.imgur.com/nm9z1J7.png
It's readable (644) and all folders in it's tree are accessible (755)
In JS console I have the following error:
`TypeError: this.mask.addClass is not a function modx.jsgrps-min.js:1:113438`
`onShow https://my_domain/admin/assets/modext/modx.jsgrps-min.js:1`
`afterShow 3 ExtJS`
`onAjaxException https://my_domain/admin/assets/modext/core/modx.js?v=01cf0b4a:122`
`fire 3 ExtJS`
`f https://my_domain/admin/assets/ext3/adapter/ext/ext-base.js:21`
`m https://my_domain/admin/assets/ext3/adapter/ext/ext-base.js:21`
`createCallback https://my_domain/admin/assets/ext3/adapter/ext/ext-base.js:21`
Seems like this error is caused by the failed ajax request

### Expected behavior
A new resource should be created in a given context

### Environment
MODX Revolution 2.7.0-pl (advanced) (worked OK with prev. v2.6.5)
ExtJS: 3.4.1
Smarty: 3.1.27
10.2.19-MariaDB
PHP: 7.2
Lightspeed, modSecurity disabled
Firefox v65, Chromium v71, Gnome's Web v3.30.2

Happens after upgrade from v2.6.5 to v.2.7.0
Please somebody give me a hint what else should I check except modSecurity (off) and file permissions.
Same [issue](https://github.com/modxcms/revolution/issues/14192#issue-389225210) is filed in MODX repo

**Comment by p-boiko** [comment]
No errors on a mirror site with the same setup. Sorry

**Comment by danfox** [comment]
I have the same problem. Babel doesn't work with Modx 2.7 and it's giving me a lot of pain and problems. :(
Is there any solution?

**Comment by zaigham** [comment]
@danfox kindly share more details, if there are any console errors and such.

**Comment by danfox** [comment]
JHi @zaigham, I have ModX 2.7 and Babel 3.0.0-pl. 
Babel is not translating anything on the site, the switcher leads always to the homepage and no translated contents are being loaded.
I haven't any error in console.
What should I look for?

**Comment by zaigham** [comment]
@danfox from the sound of it, I think js is cached in your browser. Have u made sure you cleared all possible caches?

**Comment by danfox** [comment]
I've cleaned all the possible caches. Still the same error... I really don't know what to do.

**Comment by zaigham** [comment]
@danfox maybe try this one https://github.com/modxcms/revolution/issues/14192#issuecomment-445932334

**Comment by Spheerys** [comment]
I have a similar issue : when I want to link a resource via Babel, after the resource selection and validation, the progress bar stay open without saving the change.
I'm running MODX 2.7.1 and Babel 3.0.0
